Refactor run script

diff --git a/script/run b/script/run
--- a/script/run
+++ b/script/run
@@ -1,31 +1,46 @@
-#!/bin/sh
+#!/bin/bash
+
+language=$1
+year=$2
+day=$3
+part=$4
 
 # Check the length of the day input
 # Prepend a 0 if it's less than 10 i.e 4 -> 04, 11 -> 11
-day=$3
-if [ ${#3} -le 1 ]; then
-    day=0$3
+if [ ${#day} -le 1 ]; then
+    day=0$day
 fi
+cd $year/day_$day/$language/
 
-cd $2/day_$day/
+run_python () {
+    source_file=p$part.py
+    echo "Running $year/day_$day/$output_file"
+    python3 $source_file
+}
 
-if [ $1 = "haskell" ]; then
-    source_file=p$4.hs
-    output_file=p$4.hsx
+run_haskell () {
+    source_file=p$part.hs
+    output_file=p$part.hsx
     echo "Attempting to build $source_file"
     stack ghc -- $source_file -o $output_file
     if [ $? -eq 0 ]; then
-        echo "Running $2/day_$day/$output_file\n-----\n"
+        echo "Running $year/day_$day/$output_file"
         ./$output_file
     else
-        echo "Failed to build $source_file, not running."
+        echo "Failed to build $source_file, not running"
+        exit 1
     fi
-elif [ $1 = "python" ]; then
-    source_file=p$4.py
-    echo "Running $2/day_$day/$output_file\n-----\n"
-    python3 p$4.py
-elif [ $1 = "ruby" ]; then
-    source_file=p$4.rb
-    echo "Running $2/day_$day/$output_file\n-----\n"
-    ruby p$4.rb
-fi
+}
+
+run_ruby () {
+    source_file=p$part.rb
+    echo "Running $year/day_$day/$output_file"
+    ruby $source_file
+}
+
+case $language in
+    "python") run_python;;
+    "haskell") run_haskell;;
+    "ruby") run_ruby;;
+    *) echo "No problems have been solved in the language $language"; exit 1;;
+esac
